### PR TITLE
add Device Brightness control 

### PR DESCRIPTION
**Pull request by dergelm**

### CODE REVIEW

**Comment by versx** [comment]
Personally think a trackbar would be better than only min/max.

**Comment by dergelm** [comment]
> Personally think a trackbar would be better than only min/max.

Thought about that too. But was to lazy to look up how to add a slider. And I couldn’t really think about a use case where you would something else then min or max brightness.
But feel free to add it ;)

**Comment by versx** [comment]
Why the hell do we need to control brightness though? 😂 

> > Personally think a trackbar would be better than only min/max.
> 
> Thought about that too. But was to lazy to look up how to add a slider. And I couldn’t really think about a use case where you would something else then min or max brightness.
> But feel free to add it ;)

Don't worry, I will push changes in a bit.

image

**Comment by plinytheelder** [comment]
that's nifty. any chance on a global toggle in the utilities section to overwrite all brightness settings simultaneously?

**Comment by dergelm** [comment]
> that's nifty. any chance on a global toggle in the utilities section to overwrite all brightness settings simultaneously?

check global brightness pr.

because I suck at git I didn't know how to add it to this pr^^

**Pull request merged**
